resources:
  - name: myRepoResource
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/testElements
      branches:
        include: main
pipelines:
  - name: TestElement
    configuration:
      integrations:
          - name: s_art
    steps:
      - name: TestElement_1
        type: Bash
        configuration:
          inputResources:
            - name: myRepoResource
        execution:
          onExecute:
            - save_tests "$res_myRepoResource_resourcePath/tests/junit/error.xml"
            - save_tests "$res_myRepoResource_resourcePath/tests/junit/failure.xml"
            - save_tests "$res_myRepoResource_resourcePath/tests/junit/success.xml"
            
